Add BigQuery Drop Table capability
data-integrations/google-cloud pull request #113
Opened 2019-06-06 09:33 UTC by alogvinchuk-cv

2019-06-08 19:17 UTC, nitinmotgi commented on src/main/java/io/cdap/plugin/gcp/bigquery/actions/BigQueryDropTableAction.java
> +    String tableNames = config.getTable();
tableName

2019-06-08 19:18 UTC, nitinmotgi commented on src/main/java/io/cdap/plugin/gcp/bigquery/actions/BigQueryDropTableAction.java
> +      table.delete();
Does this throw an exception, if it does catch it and provide a simplified message.

2019-06-08 19:18 UTC, nitinmotgi commented on widgets/BigQueryDropTable-action.json
> +  "display-name" : "Google Cloud BigQuery Drop Table",
BQ Drop Table. We are changing to short names.

2019-06-08 19:19 UTC, nitinmotgi commented on widgets/BigQueryDropTable-action.json
> +      "label" : "Credentials",
Advanced

2019-06-08 19:19 UTC, nitinmotgi commented on widgets/BigQueryDropTable-action.json
> +          "widget-type": "textbox",
Move this to "Advanced" section

2019-06-08 19:19 UTC, nitinmotgi commented on widgets/BigQueryDropTable-action.json
> +          "label": "Project ID",
Project Id

2019-06-11 20:36 UTC, nitinmotgi requested changes
Minor comments

2019-06-11 20:36 UTC, nitinmotgi commented on widgets/BigQueryDropTable-action.json
> +  "display-name" : "Google Cloud BQ Drop Table",
BQ Drop Table

2019-06-12 07:02 UTC, alogvinchuk-cv commented
@nitinmotgi Is this desired look of configuration window?
![image](https://user-images.githubusercontent.com/46483088/59330068-16df7780-8cf9-11e9-8d98-d8bb45c9ed22.png)

2019-06-12 07:15 UTC, alogvinchuk-cv commented
@nitinmotgi Is this desired look of configuration panel?
![image](https://user-images.githubusercontent.com/46483088/59330772-092af180-8cfb-11e9-904c-f30912c67cab.png)

2020-03-19 21:43 UTC, closed without merging