[PLUGIN-1293] Gcs plugin Bug for buckets having delete multi part upload policy.
data-integrations/google-cloud pull request #1307
Opened 2023-09-25 06:07 UTC by Shubhangi-cs

Bug:
Pipeline fails with warning and error for the GCS buckets with delete multi part upload policy.

Bugfix:
Plugin should support the buckets with this policy enabled in it. Bumped up the library version to fix this.

https://cdap.atlassian.net/browse/PLUGIN-1293

2023-10-03 03:49 UTC, itsankit-google requested changes
Please add an e2e test.

2023-10-03 20:13 UTC, itsankit-google commented
There are also two required e2e tests failures, ptal: https://github.com/data-integrations/google-cloud/actions/runs/6334790063/job/17216255525?pr=1307

```
[ERROR] Tests run: 4, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 52.683 s <<< FAILURE! - in GCS source - Validate GCS plugin output schema for different formats
[ERROR] GCS source - Validate GCS plugin output schema for different formats.GCS Source output schema validation for blob, parquet, avro and text format  Time elapsed: 14.287 s  <<< FAILURE!
java.lang.AssertionError: Schema displayed on UI should match with the expected Schema

[ERROR] GCS source - Validate GCS plugin output schema for different formats.GCS Source output schema validation for blob, parquet, avro and text format  Time elapsed: 12.998 s  <<< FAILURE!
java.lang.AssertionError: Schema displayed on UI should match with the expected Schema
```

2023-10-04 13:27 UTC, Shubhangi-cs commented
> Please add an e2e test.
 e2e test case can be added further and separate PR can be raised for the same, till then we can go ahead merging this PR.

2023-10-05 16:08 UTC, itsankit-google approved these changes
code changes lgtm, but we'll have to make sure we do pretty comprehensive testing. Browsing/sampling, service account json vs auto-detect, on dataproc vs on k8s, etc.

2023-10-05 17:12 UTC, sahusanket approved these changes

2023-10-09 11:53 UTC, merged