[PLUGIN-1739] Updated time partitioning type labels same as id
data-integrations/google-cloud pull request #1361
Opened 2024-01-25 06:18 UTC by psainics

##  Updated time partitioning type labels same as id

Jira : [Plugin-1739](https://cdap.atlassian.net/browse/PLUGIN-1739)

## Description
As id and labels were different, user faced issue when using the label as macro.
This PR makes the id and labels same.

## UI Fields changes
Labels for `Time Partitioning Type` fields are changed.
![image](https://github.com/cloudsufi/google-cloud/assets/122770897/30525496-c108-4351-9255-c57031bb23a0)

## Docs
Mention on fields are updated in docs and the field description.

~Daily~  --> Day
~Hourly~  --> Hour
~Monthly~ --> Month
~Yearly~ --> Year

2024-02-28 02:50 UTC, itsankit-google reviewed
Wondering if it is okay to also keep `DAY`, `MONTH`, `HOUR` and `YEAR` also in the map as keys so that existing pipelines don't break.

@albertshau wdyt?

2024-02-28 20:24 UTC, albertshau commented
It looks like it is handled already, since the original value is used if it's not in the map. I agree that it's not the most straightforward thing to read though. In this case I think it's more clear if we just have a switch statement rather than a map.

2024-02-28 20:24 UTC, albertshau commented on src/main/java/io/cdap/plugin/gcp/bigquery/sink/BigQuerySinkConfig.java
> +    timePartitioningTypeUpperCase  = TIME_PARTITIONING_TYPES_UI_MAP.getOrDefault(timePartitioningTypeUpperCase,
nit: extra space

2024-02-29 00:25 UTC, psainics commented on src/main/java/io/cdap/plugin/gcp/bigquery/sink/BigQuerySinkConfig.java
> +    timePartitioningTypeUpperCase  = TIME_PARTITIONING_TYPES_UI_MAP.getOrDefault(timePartitioningTypeUpperCase,
👍

2024-02-29 08:52 UTC, itsankit-google requested changes
As Albert suggested, can we please use a switch-case instead of map?

2024-02-29 10:05 UTC, psainics commented
> As Albert suggested, can we please use a switch-case instead of map?

I have removed the map for a switch, also included a unit test !

2024-03-06 03:33 UTC, itsankit-google approved these changes

2024-03-28 12:15 UTC, merged