[PLUGIN-698] Add wildcard support for copy and move action
data-integrations/google-cloud pull request #1418
Opened 2024-05-21 04:07 UTC by psainics

## Add wildcard support for copy and move action

Jira : [PLUGIN-698](https://cdap.atlassian.net/browse/PLUGIN-698)

### Description

Adding wild card support in gcs copy and move action !
eg: source path `gs://foobucket/mydir/test_web*/*`

### Code change

- Modified `StorageClient.java`
- Modified `GCSCopy.java`
- Modified `GCSMove.java`
- Modified `SourceDestConfig.java`

### Unit Tests

- Modified `StorageClientTest.java`

![image](https://github.com/data-integrations/google-cloud/assets/122770897/514815ed-9506-46c8-86a1-669d526f5ff8)

2024-05-28 12:44 UTC, sahusanket commented on src/test/java/io/cdap/plugin/gcp/gcs/StorageClientTest.java
> +    Assert.assertEquals(3, filterMatchedPaths.size());
Small Doubt : `"mydir/test_web2/css/foo.css"` is not coming here. 

According to line 196 in  StorageCLient  is should match right?

2024-05-28 12:55 UTC, psainics commented on src/test/java/io/cdap/plugin/gcp/gcs/StorageClientTest.java
> +    Assert.assertEquals(3, filterMatchedPaths.size());
This is expected , single * only matches one level deep !

![image](https://github.com/data-integrations/google-cloud/assets/122770897/3d8afe46-adc1-4b19-a0f1-74936075b94a)

https://www.digitalocean.com/community/tools/glob

2024-05-29 06:08 UTC, psainics commented on src/test/java/io/cdap/plugin/gcp/gcs/StorageClientTest.java
> +    Assert.assertEquals(3, filterMatchedPaths.size());
These are glob expression not regex !

2024-05-29 07:03 UTC, sahusanket commented on src/test/java/io/cdap/plugin/gcp/gcs/StorageClientTest.java
> +    Assert.assertEquals(3, filterMatchedPaths.size());
Got it. Thanks for clarification

2024-06-03 09:42 UTC, itsankit-google requested changes
Please update documentation as well with examples.

2024-06-07 10:00 UTC, psainics commented
> Please update documentation as well with examples.

Updated !

![image](https://github.com/data-integrations/google-cloud/assets/122770897/8dff47d6-b5ea-4eb5-a289-275c83c0ef3e)
![image](https://github.com/data-integrations/google-cloud/assets/122770897/955480eb-9fcb-4b49-b578-a8f2f5ea7b9b)

2024-06-10 06:40 UTC, itsankit-google approved these changes

2024-06-12 03:41 UTC, merged