GCS Source additional scenarios.
data-integrations/google-cloud pull request #1470
Opened 2024-12-09 11:31 UTC by bijay27bit

@itsankit-google Please review the GCS source additional scenarios.

Thanks

2024-12-09 12:01 UTC, itsankit-google reviewed
why can't we combine scenarios `To verify successful records transfer from GCS source to BigQuery sink with macro fields enabled at source` and `To verify successful data transfer from GCS to BigQuery with macro Path Field`?

2024-12-10 05:54 UTC, bijay27bit commented
> why can't we combine scenarios `To verify successful records transfer from GCS source to BigQuery sink with macro fields enabled at source` and `To verify successful data transfer from GCS to BigQuery with macro Path Field`?

Thanks Ankit,

The test data used for the 'path field' was not supported. Following an internal discussion with the team, a separate scenario was created to ensure coverage.

2024-12-10 06:24 UTC, itsankit-google commented
> > why can't we combine scenarios `To verify successful records transfer from GCS source to BigQuery sink with macro fields enabled at source` and `To verify successful data transfer from GCS to BigQuery with macro Path Field`?
> 
> Thanks Ankit,
> 
> The test data used for the 'path field' was not supported. Following an internal discussion with the team, a separate scenario was created to ensure coverage.

What do you mean by `testdata` not supported? @itsmekumari @AnkitCLI can you provide more clarification?

2024-12-10 06:25 UTC, itsankit-google requested changes
PTAL at test failures.

2024-12-10 07:03 UTC, itsmekumari commented
> > > why can't we combine scenarios `To verify successful records transfer from GCS source to BigQuery sink with macro fields enabled at source` and `To verify successful data transfer from GCS to BigQuery with macro Path Field`?
> > 
> > 
> > Thanks Ankit,
> > The test data used for the 'path field' was not supported. Following an internal discussion with the team, a separate scenario was created to ensure coverage.
> 
> What do you mean by `testdata` not supported? @itsmekumari @AnkitCLI can you provide more clarification?

I think, reference was taken from the existing test case for path field scenario. @bijay27bit you can add any path field column name and add the same in output schema which is set as macro in same scenario.

2024-12-10 13:14 UTC, bijay27bit commented
> > > > why can't we combine scenarios `To verify successful records transfer from GCS source to BigQuery sink with macro fields enabled at source` and `To verify successful data transfer from GCS to BigQuery with macro Path Field`?
> > > 
> > > 
> > > Thanks Ankit,
> > > The test data used for the 'path field' was not supported. Following an internal discussion with the team, a separate scenario was created to ensure coverage.
> > 
> > 
> > What do you mean by `testdata` not supported? @itsmekumari @AnkitCLI can you provide more clarification?
> 
> I think, reference was taken from the existing test case for path field scenario. @bijay27bit you can add any path field column name and add the same in output schema which is set as macro in same scenario.

Merged both the scenario and it is running at local branch now. Looking below test failures as per Ankit's comment. Thanks

2024-12-10 13:22 UTC, itsankit-google commented
> PTAL at test failures.

Also the count of records transferred is zero in failing tests, not sure if it is expected.
![image](https://github.com/user-attachments/assets/997221e7-b844-4516-9a55-7427b530fe02)

2024-12-11 06:54 UTC, bijay27bit commented
> > PTAL at test failures.
> 
> Also the count of records transferred is zero in failing tests, not sure if it is expected. ![image](https://private-user-images.githubusercontent.com/88528384/394290014-997221e7-b844-4516-9a55-7427b530fe02.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM5MDAyMjYsIm5iZiI6MTczMzg5OTkyNiwicGF0aCI6Ii84ODUyODM4NC8zOTQyOTAwMTQtOTk3MjIxZTctYjg0NC00NTE2LTlhNTUtNzQyN2I1MzBmZTAyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjExVDA2NTIwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY2ZDJiMDQ1ZGFjZTQ1MDVjN2FmMzlkYzgxNDU2NmUwZDQ0MjI4NjBlYTI0MTZiOTAzNjUzYThjOWU1MDVlZTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.dsG-H9acozXuBo2LUQ0YtYgX34kBlqv_u4zjd8CzPxA)

Hi @itsankit-google I have made the changes and above failed test scenarios are not created by me. Please review the latest code. Thanks

2024-12-14 07:32 UTC, itsankit-google commented on src/e2e-test/features/gcs/source/GCSSourceToBigQuery.feature
> +  Scenario:To verify successful records transfer from GCS source to BigQuery sink with macro fields enabled at source
No of records transferred is `0` in this test, is it expected?

![image](https://github.com/user-attachments/assets/130ef161-65db-4683-90f6-3b87e91310b9)

2025-01-06 08:15 UTC, bijay27bit commented
@itsankit-google
Record transferred successfully from GCS to BigQuery.
Please review and approve for final merge.
Thanks

2025-01-07 12:18 UTC, itsankit-google approved these changes
LGTM

2025-01-07 12:18 UTC, merged