Gcs related Feature files and step design
data-integrations/google-cloud pull request #834
Opened 2021-11-25 11:51 UTC by sumitsri12

This PR needs to be reviewed by internal Cloudsufi team only
@sumitnigamcs

2021-11-26 04:14 UTC, sumitnigamcs requested changes

2021-11-26 04:14 UTC, sumitnigamcs commented on src/e2e-test/features/GCSRuntime.feature
> +#    Then validate failedMessage is displayed
remove this commented line

2021-11-26 04:14 UTC, sumitnigamcs commented on src/e2e-test/features/GCSRuntime.feature
> +    Then validate successMessage is displayed
have you executed mvn verify command? look like some checkstyle issues are there

2021-11-26 04:14 UTC, sumitnigamcs commented on src/e2e-test/java/io/cdap/plugin/gcs/stepsdesign/GCSConnector.java
> +    CdfGcsActions.enterPathfield(CdapUtils.pluginProp("gcspathField"));
correct the camelCasing.....go through Ragini's PR and check my comments

2021-11-26 04:14 UTC, sumitnigamcs commented on src/e2e-test/java/io/cdap/plugin/gcs/stepsdesign/package-info.java
> +
why new line here

2021-12-01 05:20 UTC, sawantpritam requested changes

2021-12-01 05:20 UTC, sawantpritam commented on src/e2e-test/features/GCSError.feature
> +    Then Verify path is mandatory
No newline at end of file.

2021-12-01 05:20 UTC, sawantpritam commented on src/e2e-test/features/GCSRuntime.feature
> +    Then Validate successMessage is displayed
No newline at end of file.

2021-12-01 05:20 UTC, sawantpritam commented on src/e2e-test/java/io/cdap/plugin/gcs/stepsdesign/GCSConnector.java
> +  @Then("verify the schema in output")
verify -> Verify

2021-12-01 05:20 UTC, sawantpritam commented on src/e2e-test/java/io/cdap/plugin/gcs/stepsdesign/GCSConnector.java
> +  @Then("verify the datatype")
verify -> Verify

2021-12-01 05:20 UTC, sawantpritam commented on src/e2e-test/resources/errorMessage.properties
> +errorMessagePath=Required property 'path' has no value.
No newline at end of file.

2021-12-06 07:35 UTC, closed without merging