Gcs multifile related test cases
data-integrations/google-cloud pull request #837
Opened 2021-11-29 15:20 UTC by sumitsri12

@sumitnigamcs

2021-12-01 05:04 UTC, sawantpritam requested changes

2021-12-01 05:04 UTC, sawantpritam commented on src/e2e-test/features/GCSMultifileError.feature
> +    Then Verify path validation
No New line at end of file. Add empty line

2021-12-01 05:04 UTC, sawantpritam commented on src/e2e-test/features/GcsMultifile.feature
> +  Scenario: User is able to Login and confirm data is getting transferred from BigQuery to GcsMultifile
Change scenario description. Steps are for GCS to GCSMultifile

2021-12-01 05:04 UTC, sawantpritam commented on src/e2e-test/features/GcsMultifile.feature
> +  Scenario: User is able to Login and confirm data is getting transferred from BigQuery to GcsMultifile
Change scenario description.

2021-12-01 05:04 UTC, sawantpritam commented on src/e2e-test/features/GcsMultifile.feature
> +  Scenario: User is able to Login and confirm data is getting transferred from BigQuery to GcsMultifile
Change scenario description... check for all subsequent scenarios as well.

2021-12-01 05:04 UTC, sawantpritam commented on src/e2e-test/java/io/cdap/plugin/gcsmultifile/actions/BigQueryMulifileActions.java
> +  public static void enterdatasetProjectId() throws IOException {
Check camelcase. enterdatasetProjectId -> enterDatasetProjectId

2021-12-01 05:04 UTC, sawantpritam commented on src/e2e-test/java/io/cdap/plugin/gcsmultifile/actions/BigQueryMulifileActions.java
> +package io.cdap.plugin.gcsmultifile.actions;
Add licence

2021-12-01 05:04 UTC, sawantpritam commented on src/e2e-test/java/io/cdap/plugin/gcsmultifile/locators/GCSMultifileLocators.java
> +package io.cdap.plugin.gcsmultifile.locators;
Add Licence.

2021-12-01 05:04 UTC, sawantpritam commented on src/e2e-test/java/io/cdap/plugin/gcsmultifile/stepsdesign/GCSMultifileConnector.java
> +package io.cdap.plugin.gcsmultifile.stepsdesign;
Add licence.

2021-12-01 05:04 UTC, sawantpritam commented on src/e2e-test/java/io/cdap/plugin/gcsmultifile/stepsdesign/GCSMultifileConnector.java
> +  @Then("Verify the pipeline status in each case")
remove if unused.

2021-12-01 05:04 UTC, sawantpritam commented on src/e2e-test/java/io/cdap/plugin/gcsmultifile/stepsdesign/GCSMultifileConnector.java
> +  @Then("validate successMessage is displayed")
validate ->Validate

2021-12-01 05:04 UTC, sawantpritam commented on src/e2e-test/resources/errorMessage.properties
> +errorMessagePath=Required property 'path' has no value.
No new line at the end of file. add empty line.

2021-12-01 13:22 UTC, sumitnigamcs requested changes

2021-12-01 13:22 UTC, sumitnigamcs commented on src/e2e-test/features/GCSMultifileError.feature
> +    Then Verify path validation
looks like checkstyle issues are there, please verify

2021-12-01 13:22 UTC, sumitnigamcs commented on src/e2e-test/features/GcsMultifile.feature
> +
remove the extra lines here

2021-12-01 13:22 UTC, sumitnigamcs commented on src/e2e-test/java/io/cdap/plugin/gcsmultifile/actions/package-info.java
> +
remove extra line here

2021-12-01 13:22 UTC, sumitnigamcs commented on src/e2e-test/java/io/cdap/plugin/gcsmultifile/locators/GCSMultifileLocators.java
> +package io.cdap.plugin.gcsmultifile.locators;
looks like there are no licenses in the files. checkstyle not run it seems

2021-12-01 13:22 UTC, sumitnigamcs commented on src/e2e-test/java/io/cdap/plugin/gcsmultifile/locators/GCSMultifileLocators.java
> +  public static WebElement ProjectId;
camelcasing correction

2021-12-01 13:22 UTC, sumitnigamcs commented on src/e2e-test/java/io/cdap/plugin/gcsmultifile/locators/package-info.java
> +
remove extra line here

2021-12-01 13:22 UTC, sumitnigamcs commented on src/e2e-test/java/io/cdap/plugin/gcsmultifile/locators/GCSMultifileLocators.java
> +
remove extra lines here

2021-12-01 13:22 UTC, sumitnigamcs commented on src/e2e-test/java/io/cdap/plugin/gcsmultifile/actions/BigQueryMulifileActions.java
> +  public static void enterdatasetProjectId() throws IOException {
camelcasing correction

2021-12-01 13:22 UTC, sumitnigamcs commented on src/e2e-test/java/io/cdap/plugin/gcsmultifile/stepsdesign/GCSMultifileConnector.java
> +    out.close();
close this in the finally block

2021-12-06 10:14 UTC, ksahilCF commented on src/e2e-test/features/GcsMultifile.feature
> +
all the scenario have same description

2021-12-29 06:59 UTC, closed without merging