0.18 with dataplex plugins
data-integrations/google-cloud pull request #969
Opened 2022-04-12 14:21 UTC by vikasrathee-cs

0.18 with dataplex plugins

2022-04-15 04:29 UTC, rmstar approved these changes

2022-04-15 04:31 UTC, rmstar requested changes
Can we also cherrypick https://github.com/data-integrations/google-cloud/pull/968?

2022-04-15 09:58 UTC, vikasrathee-cs commented
Changes done.

2022-04-18 17:33 UTC, rmstar approved these changes

2022-04-18 17:33 UTC, merged